micronaut:
  application:
    name: saas-counter
  server:
    port: 9292
    netty:
      worker:
        threads: 4
        event-loop-threads: 2
  executors:
    default:
      type: fixed
      core-pool-size: 4
      max-pool-size: 10
      queue-size: 100
      virtual: true
    io:
      type: cached
      core-pool-size: 8
      max-pool-size: 64
      queue-size: 500
      virtual: true
    cpu:
      type: fixed
      core-pool-size: 16
      max-pool-size: 32
      queue-size: 1000
      virtual: true
  otel:
    traces:
      exporter: otlp
    exporter:
      otlp:
        endpoint: ${JAEGER_URL:`http://localhost:4317`}

grpc:
  server:
    port: 7575

rabbitmq:
  host: ${RABBITMQ_HOST:localhost}
  port: ${RABBITMQ_PORT:5672}
  username: rabbitmq
  password: rabbitmq
